# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 305)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 160, 181, 131))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.given_as_label = QtWidgets.QLabel(self.groupBox)
        self.given_as_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.given_as_label.setObjectName("given_as_label")
        self.gridLayout_3.addWidget(self.given_as_label, 0, 0, 1, 1)
        self.given_as_entry = QtWidgets.QLineEdit(self.groupBox)
        self.given_as_entry.setObjectName("given_as_entry")
        self.gridLayout_3.addWidget(self.given_as_entry, 0, 1, 1, 1)
        self.given_as_unit = QtWidgets.QLabel(self.groupBox)
        self.given_as_unit.setObjectName("given_as_unit")
        self.gridLayout_3.addWidget(self.given_as_unit, 0, 2, 1, 1)
        self.given_cd_label = QtWidgets.QLabel(self.groupBox)
        self.given_cd_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.given_cd_label.setObjectName("given_cd_label")
        self.gridLayout_3.addWidget(self.given_cd_label, 1, 0, 1, 1)
        self.given_cd_entry = QtWidgets.QLineEdit(self.groupBox)
        self.given_cd_entry.setObjectName("given_cd_entry")
        self.gridLayout_3.addWidget(self.given_cd_entry, 1, 1, 1, 1)
        self.given_cd_unit = QtWidgets.QLabel(self.groupBox)
        self.given_cd_unit.setObjectName("given_cd_unit")
        self.gridLayout_3.addWidget(self.given_cd_unit, 1, 2, 1, 1)
        self.given_pb_label = QtWidgets.QLabel(self.groupBox)
        self.given_pb_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.given_pb_label.setObjectName("given_pb_label")
        self.gridLayout_3.addWidget(self.given_pb_label, 2, 0, 1, 1)
        self.given_pb_entry = QtWidgets.QLineEdit(self.groupBox)
        self.given_pb_entry.setObjectName("given_pb_entry")
        self.gridLayout_3.addWidget(self.given_pb_entry, 2, 1, 1, 1)
        self.given_pb_unit = QtWidgets.QLabel(self.groupBox)
        self.given_pb_unit.setObjectName("given_pb_unit")
        self.gridLayout_3.addWidget(self.given_pb_unit, 2, 2, 1, 1)
        self.given_hg_label = QtWidgets.QLabel(self.groupBox)
        self.given_hg_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.given_hg_label.setObjectName("given_hg_label")
        self.gridLayout_3.addWidget(self.given_hg_label, 3, 0, 1, 1)
        self.given_hg_entry = QtWidgets.QLineEdit(self.groupBox)
        self.given_hg_entry.setObjectName("given_hg_entry")
        self.gridLayout_3.addWidget(self.given_hg_entry, 3, 1, 1, 1)
        self.given_hg_unit = QtWidgets.QLabel(self.groupBox)
        self.given_hg_unit.setObjectName("given_hg_unit")
        self.gridLayout_3.addWidget(self.given_hg_unit, 3, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 160, 142, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.calc_as_label = QtWidgets.QLabel(self.groupBox_2)
        self.calc_as_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calc_as_label.setObjectName("calc_as_label")
        self.gridLayout.addWidget(self.calc_as_label, 0, 0, 1, 1)
        self.calc_as_value = QtWidgets.QLabel(self.groupBox_2)
        self.calc_as_value.setObjectName("calc_as_value")
        self.gridLayout.addWidget(self.calc_as_value, 0, 1, 1, 1)
        self.calc_as_unit = QtWidgets.QLabel(self.groupBox_2)
        self.calc_as_unit.setObjectName("calc_as_unit")
        self.gridLayout.addWidget(self.calc_as_unit, 0, 2, 1, 1)
        self.calc_cd_label = QtWidgets.QLabel(self.groupBox_2)
        self.calc_cd_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calc_cd_label.setObjectName("calc_cd_label")
        self.gridLayout.addWidget(self.calc_cd_label, 1, 0, 1, 1)
        self.calc_cd_value = QtWidgets.QLabel(self.groupBox_2)
        self.calc_cd_value.setObjectName("calc_cd_value")
        self.gridLayout.addWidget(self.calc_cd_value, 1, 1, 1, 1)
        self.calc_cd_unit = QtWidgets.QLabel(self.groupBox_2)
        self.calc_cd_unit.setObjectName("calc_cd_unit")
        self.gridLayout.addWidget(self.calc_cd_unit, 1, 2, 1, 1)
        self.calc_pb_label = QtWidgets.QLabel(self.groupBox_2)
        self.calc_pb_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calc_pb_label.setObjectName("calc_pb_label")
        self.gridLayout.addWidget(self.calc_pb_label, 2, 0, 1, 1)
        self.calc_pb_value = QtWidgets.QLabel(self.groupBox_2)
        self.calc_pb_value.setObjectName("calc_pb_value")
        self.gridLayout.addWidget(self.calc_pb_value, 2, 1, 1, 1)
        self.calc_pb_unit = QtWidgets.QLabel(self.groupBox_2)
        self.calc_pb_unit.setObjectName("calc_pb_unit")
        self.gridLayout.addWidget(self.calc_pb_unit, 2, 2, 1, 1)
        self.calc_hg_label = QtWidgets.QLabel(self.groupBox_2)
        self.calc_hg_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calc_hg_label.setObjectName("calc_hg_label")
        self.gridLayout.addWidget(self.calc_hg_label, 3, 0, 1, 1)
        self.calc_hg_value = QtWidgets.QLabel(self.groupBox_2)
        self.calc_hg_value.setObjectName("calc_hg_value")
        self.gridLayout.addWidget(self.calc_hg_value, 3, 1, 1, 1)
        self.calc_hg_unit = QtWidgets.QLabel(self.groupBox_2)
        self.calc_hg_unit.setObjectName("calc_hg_unit")
        self.gridLayout.addWidget(self.calc_hg_unit, 3, 2, 1, 1)
        self.header = QtWidgets.QLabel(Dialog)
        self.header.setGeometry(QtCore.QRect(20, 10, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 30, 351, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 50, 241, 22))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.weight_label = QtWidgets.QLabel(self.widget)
        self.weight_label.setObjectName("weight_label")
        self.gridLayout_4.addWidget(self.weight_label, 0, 0, 1, 1)
        self.weight_entry = QtWidgets.QLineEdit(self.widget)
        self.weight_entry.setObjectName("weight_entry")
        self.gridLayout_4.addWidget(self.weight_entry, 0, 1, 1, 1)
        self.weight_combo = QtWidgets.QComboBox(self.widget)
        self.weight_combo.setObjectName("weight_combo")
        self.weight_combo.addItem("")
        self.weight_combo.addItem("")
        self.weight_combo.addItem("")
        self.weight_combo.addItem("")
        self.gridLayout_4.addWidget(self.weight_combo, 0, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(30, 90, 114, 48))
        self.widget1.setObjectName("widget1")
        self.formLayout = QtWidgets.QFormLayout(self.widget1)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.from_label = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_label.sizePolicy().hasHeightForWidth())
        self.from_label.setSizePolicy(sizePolicy)
        self.from_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.from_label.setObjectName("from_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.from_label)
        self.from_combo = QtWidgets.QComboBox(self.widget1)
        self.from_combo.setObjectName("from_combo")
        self.from_combo.addItem("")
        self.from_combo.addItem("")
        self.from_combo.addItem("")
        self.from_combo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.from_combo)
        self.to_label = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_label.sizePolicy().hasHeightForWidth())
        self.to_label.setSizePolicy(sizePolicy)
        self.to_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.to_label.setObjectName("to_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.to_label)
        self.to_combo = QtWidgets.QComboBox(self.widget1)
        self.to_combo.setObjectName("to_combo")
        self.to_combo.addItem("")
        self.to_combo.addItem("")
        self.to_combo.addItem("")
        self.to_combo.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.to_combo)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.weight_entry, self.given_as_entry)
        Dialog.setTabOrder(self.given_as_entry, self.given_cd_entry)
        Dialog.setTabOrder(self.given_cd_entry, self.given_pb_entry)
        Dialog.setTabOrder(self.given_pb_entry, self.given_hg_entry)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Given"))
        self.given_as_label.setText(_translate("Dialog", "Arsenic:"))
        self.given_as_unit.setText(_translate("Dialog", "ppm"))
        self.given_cd_label.setText(_translate("Dialog", "Cadmium:"))
        self.given_cd_unit.setText(_translate("Dialog", "ppm"))
        self.given_pb_label.setText(_translate("Dialog", "Lead:"))
        self.given_pb_unit.setText(_translate("Dialog", "ppm"))
        self.given_hg_label.setText(_translate("Dialog", "Mercury:"))
        self.given_hg_unit.setText(_translate("Dialog", "ppm"))
        self.groupBox_2.setTitle(_translate("Dialog", "Calculated"))
        self.calc_as_label.setText(_translate("Dialog", "Arsenic:"))
        self.calc_as_value.setText(_translate("Dialog", "0.0"))
        self.calc_as_unit.setText(_translate("Dialog", "ppm"))
        self.calc_cd_label.setText(_translate("Dialog", "Cadmium:"))
        self.calc_cd_value.setText(_translate("Dialog", "0.0"))
        self.calc_cd_unit.setText(_translate("Dialog", "ppm"))
        self.calc_pb_label.setText(_translate("Dialog", "Lead:"))
        self.calc_pb_value.setText(_translate("Dialog", "0.0"))
        self.calc_pb_unit.setText(_translate("Dialog", "ppm"))
        self.calc_hg_label.setText(_translate("Dialog", "Mercury:"))
        self.calc_hg_value.setText(_translate("Dialog", "0.0"))
        self.calc_hg_unit.setText(_translate("Dialog", "ppm"))
        self.header.setText(_translate("Dialog", "Heavy Metals Unit Converter"))
        self.weight_label.setText(_translate("Dialog", "Weight:"))
        self.weight_combo.setItemText(0, _translate("Dialog", "mg/serving"))
        self.weight_combo.setItemText(1, _translate("Dialog", "g/serving"))
        self.weight_combo.setItemText(2, _translate("Dialog", "mg/capsule"))
        self.weight_combo.setItemText(3, _translate("Dialog", "mg/tablet"))
        self.from_label.setText(_translate("Dialog", "From:"))
        self.from_combo.setItemText(0, _translate("Dialog", "ppm"))
        self.from_combo.setItemText(1, _translate("Dialog", "ug/serving"))
        self.from_combo.setItemText(2, _translate("Dialog", "ug/capsule"))
        self.from_combo.setItemText(3, _translate("Dialog", "ug/tablet"))
        self.to_label.setText(_translate("Dialog", "To:"))
        self.to_combo.setItemText(0, _translate("Dialog", "ppm"))
        self.to_combo.setItemText(1, _translate("Dialog", "ug/serving"))
        self.to_combo.setItemText(2, _translate("Dialog", "ug/capsule"))
        self.to_combo.setItemText(3, _translate("Dialog", "ug/tablet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

